name: Kirby 64 CI

on:
  push:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout reposistory
      uses: actions/checkout@master
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: Download Qemu Irix
      run: wget https://github.com/n64decomp/qemu-irix/releases/download/v2.11-deb/qemu-irix-2.11.0-2169-g32ab296eef_amd64.deb
    - name: Install Qemu Irix
      run: sudo dpkg -i qemu-irix-2.11.0-2169-g32ab296eef_amd64.deb
    - name: Install Dependencies
      run: sudo apt install -y binutils-mips-linux-gnu build-essential git libcapstone-dev pkgconf python3
    - name: Save Baserom Key
      run: 'echo "$BASEROMKEY" > key'
      env:
        BASEROMKEY: ${{secrets.BASEROMKEY}}
    - name: Clone Baserom
      run: GIT_SSH_COMMAND='ssh -i key -o IdentitiesOnly=yes' git clone git@github.com:Mr-Wiseguy/kirby64-secret.git
    - name: Copy Baserom
      run: cp kirby64-secret/baserom.us.z64 .
    - name: Build Libultra
      run: make -C libreultra -j4
    - name: Build Naudio
      run: make -C libreultra naudio -j4
    - name: Build Tools
      run: make -C tools -j4
    - name: Assemble F3DEX2
      run: make -C f3dex2 VERSION=2.04H ARMIPS=../tools/armips
    - name: Build Kirby 64
      run: make -j4
